In [3]:
from utils import get_processed_metadata
import pandas as pd
from typing import Iterable, List

In [4]:
processed_data_df = get_processed_metadata("./openai_processed_data")
processed_data_df

,tweet_id,row_num,category,subcategory,sentiment,tweet_language
0,@VoPP_ANZ_2019-04-24T00:01:01.000Z,0,NaN,NaN,Neutral,English
1,@SofiaCoscaron_2022-08-05T00:58:07.000Z,1,NaN,NaN,Neutral,English
2,@3DPProfessor_2021-10-27T04:52:16.000Z,2,NaN,NaN,Neutral,English
3,@arc_nwc_2019-09-19T12:57:34.000Z,3,NaN,NaN,Positive,English
4,@MACx3D_2019-11-18T17:47:09.000Z,4,NaN,NaN,Positive,English
...,...,...,...,...,...,...
1098022,@3dprintercafe_2014-07-03T05:03:35.000Z,1098022,NaN,NaN,Positive,English
1098023,@APD_Mike_2016-10-08T22:51:56.000Z,1098023,NaN,NaN,Positive,English
1098024,@Nexa3D_2019-05-14T20:57:48.000Z,1098024,NaN,NaN,Neutral,English
1098025,@Nexa3D_2019-05-01T15:00:50.000Z,1098025,NaN,NaN,Neutral,English
1098026,@Nexa3D_2019-05-01T15:00:50.000Z,1098026,NaN,NaN,Neutral,English

In [ ]:
### Validate That

In [12]:
# ---------------------------------------------------------------------------
# (Optional) master list of allowed sub-categories taken from your prompt
ALLOWED_SUBCATEGORIES: dict[str, List[str]] = {
    "Use-case": [
        "Motor Vehicles / Automotive",
        "Aerospace",
        "Industrial / Business Machines",
        "Consumer Products / Electronics",
        "Medical / Dental",
        "Academic Institutions",
        "Government / Military",
        "Architectural",
        "Power / Energy",
        "Home & DIY (Consumer / Hobbyist)",
        "Other",
    ],
    "Business-relevant": [
        "Supply Chain, Manufacturing & Logistics",
        "Cost Models & Pricing",
        "Intellectual Property & Patents",
        "Mergers, Acquisitions & Partnerships",
        "Investment & Financing",
        "Business Models",
        "Customer Adoption & Demand Dynamics",
        "Sustainability & Circular Economy",
        "Other",
    ],
    "Technological": [
        "Materials",
        "Printing Processes",
        "Hardware & Equipment",
        "Software & Design Tools",
        "Process Monitoring & Control",
        "Post-Processing Techniques",
        "AI & Digital Twin Integration",
        "Other",
    ],
    "N/A": ["N/A"],
}
# ---------------------------------------------------------------------------


def find_invalid_subcategories(
    df: pd.DataFrame,
    main_category: str,
    valid_subcategories: Iterable[str] | None = None,
    *,
    main_col: str = "category",
    sub_col: str = "subcategory",
) -> pd.DataFrame:
    """
    Return all records where `main_col` == main_category but `sub_col`
    is NOT in the allowed list.

    Parameters
    ----------
    df : pandas.DataFrame
        Your processed tweets.
    main_category : str
        The top-level category to test (e.g. "Use-case").
    valid_subcategories : Iterable[str] | None, default None
        Explicit list of allowed subs.  If None, the function will look up
        `ALLOWED_SUBCATEGORIES[main_category]`.
    main_col : str, default "classification"
        Column holding the top-level category.
    sub_col : str,  default "subclassification"
        Column holding the sub-category.

    Returns
    -------
    pandas.DataFrame
        All violating rows (same columns as the original `df`).
    """
    if valid_subcategories is None:
        try:
            valid_subcategories = ALLOWED_SUBCATEGORIES[main_category]
        except KeyError as e:
            raise ValueError(
                f"No built-in sub-category list for {main_category!r}; "
                "please supply `valid_subcategories` explicitly."
            ) from e

    mask_main = df[main_col] == main_category
    mask_bad = ~df[sub_col].isin(valid_subcategories)
    return df.loc[mask_main & mask_bad]


bad_use_case_rows = find_invalid_subcategories(processed_data_df, "Business-relevant")
bad_use_case_rows.head()

Empty DataFrame
Columns: [tweet_id, row_num, category, subcategory, sentiment, tweet_language]
Index: []